# Generated by Django 5.0.6 on 2024-07-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0003_alter_tour_description_alter_tour_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
    ]
