# Generated by Django 5.0.6 on 2024-07-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0004_alter_tour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
