# Generated by Django 5.0.6 on 2024-07-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0005_alter_category_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'тур', 'verbose_name_plural': 'туры'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='travel_tour.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tour_images', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=200, verbose_name='местоположение'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(to='travel_tour.tag', verbose_name='теги'),
        ),
    ]
